config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kids do
    resources :daily_chores
  end
  resources :chores

  # Defines the root path route ("/")
  root 'dashboard#index'
end

app/models/daily_chore.rb
# frozen_string_literal: true

class DailyChore < ApplicationRecord
  belongs_to :chore
  belongs_to :kid

  scope :for_period, ->(date_range) { where(created_at: date_range) }
  scope :for_week, ->(week) { for_period(week) }
  scope :for_this_week, -> { for_period(Date.current.all_week) }

  scope :for_day, ->(date) { for_period(date.all_day) }
  scope :for_today, -> { for_day(Date.current) }

  scope :for_chore, ->(chore) { where(chore:) }
end

app/controllers/daily_chores_controller.rb
# frozen_string_literal: true

class DailyChoresController < ApplicationController
  before_action :set_kid
  before_action :set_daily_chore, only: %i[destroy]
  before_action :set_chore_and_day, only: %i[destroy]
  after_action :set_chore_and_day, only: %i[create]

  # GET /daily_chores or /daily_chores.json
  def index
    week = (params[:date]&.to_date || Date.current).all_week

    @week = Week.new(kid: @kid, week:)
  end

  # GET /daily_chores/new
  def new
    @daily_chore = DailyChore.new(created_at: Time.current)
  end

  # POST /daily_chores or /daily_chores.json
  def create
    @daily_chore = DailyChore.where(
      daily_chore_params.merge(
        kid_id: @kid.id,
        created_at: Time.current
      )
    ).first_or_initialize

    respond_to do |format|
      format.turbo_stream if @daily_chore.save
    end
  end

  # DELETE /daily_chores/1 or /daily_chores/1.json
  def destroy
    @daily_chore.destroy

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_kid
    @kid = Kid.find(params[:kid_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_daily_chore
    @daily_chore = DailyChore.find(params[:id])
  end

  def set_chore_and_day
    @chore = @daily_chore.chore
    @day = @daily_chore.created_at.to_date
  end

  # Only allow a list of trusted parameters through.
  def daily_chore_params
    params.require(:daily_chore).permit(:chore_id, :created_at)
  end
end

app/helpers/daily_chores_helper.rb
# frozen_string_literal: true

module DailyChoresHelper
end

app/views/daily_chores/_daily_chore.html.erb
<% daily_chore = kid.daily_chores.for_chore(chore).for_today.first %>

<div data-controller="dashboard" class="px-3 py-2 d-flex flex-row gap-2">
  <div style="display: none;">
    <%= button_to 'enable', kid_daily_chores_path(kid), method: :post, data: { 'dashboard-target': 'enableButton' }, params: { daily_chore: { chore_id: chore.id } } %>
    <% if daily_chore %>
      <%= button_to 'disable', kid_daily_chore_path(kid, daily_chore), method: :delete, data: { 'dashboard-target': 'disableButton' } %>
    <% end %>
  </div>

  <div class="form-check form-switch">
    <input
    class="form-check-input"
    type="checkbox"
    role="switch"
    data-action="change->dashboard#change"
    name="daily_chore[completed]"
    <%= daily_chore ? ' checked="checked"' : '' %> />
  </div>

  <%= chore.name %>
</div>

app/views/daily_chores/_form.html.erb
<%= form_with model: [@kid, daily_chore] do |form| %>
  <div class="input-group mb-3">
    <%= form.label :chore, class: 'input-group-text' %>
    <%= form.collection_select :chore_id, Chore.order(:name), :id, :name, { prompt: t('app.select') }, {class: 'form-select'} %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :created_at, class: 'input-group-text' %>

    <%= form.text_field :created_at,
      data: {
        controller: "flatpickr",
        flatpickr_min_date: Date.current.prev_month,
        flatpickr_max_date: Date.current.tomorrow,
        flatpickr_date_format: "Y-m-d",
        flatpickr_alt_format: "Y-m-d",
      },
      class: 'form-control' %>
  </div>

  <%= button_tag submit: true, class: 'btn btn-outline-dark' do %>
    <%= icon('fa-solid', 'save') %>
    <%= t('app.save') %>
  <% end %>
  <%= link_to root_path, class: 'btn btn-outline-secondary' do %>
    <%= icon('fa-solid', 'times') %>
    <%= t('app.cancel') %>
  <% end %>
<% end %>

app/views/daily_chores/create.turbo_stream.erb
<%= turbo_stream.update ['kid', @kid.id, 'chore', @daily_chore.chore_id].join('_'), partial: "daily_chore", locals: { kid: @kid, chore: @daily_chore.chore } %>

app/views/daily_chores/destroy.turbo_stream.erb
<%= turbo_stream.update ['kid', @kid.id, 'chore', @daily_chore.chore_id].join('_'), partial: "daily_chore", locals: { kid: @kid, chore: @daily_chore.chore } %>

app/views/daily_chores/edit.html.erb
<h1>Editing daily chore</h1>

<%= render "form", daily_chore: @daily_chore %>

<br>

<div>
  <%= link_to "Show this daily chore", @daily_chore %> |
  <%= link_to "Back to daily chores", daily_chores_path %>
</div>

app/views/daily_chores/index.html.erb
<h1><%= t('app.week') %></h1>

<%= turbo_frame_tag 'week' do %>
  <%= render 'chores_table', week: @week, kid: @kid %>
<% end %>

app/views/daily_chores/new.html.erb
<%= turbo_frame_tag(@kid, 'new-chore') do %>
  <%= render "form", daily_chore: @daily_chore %>
<% end %>

app/views/daily_chores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @daily_chore %>

<div>
  <%= link_to "Edit this daily chore", edit_daily_chore_path(@daily_chore) %> |
  <%= link_to "Back to daily chores", daily_chores_path %>

  <%= button_to "Destroy this daily chore", @daily_chore, method: :delete %>
</div>