config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kids do
    resources :daily_chores
  end
  resources :chores

  # Defines the root path route ("/")
  root 'dashboard#index'
end

app/models/kid.rb
# frozen_string_literal: true

class Kid < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, uniqueness: { scope: %i[user_id] }

  has_many :kid_chores, dependent: :destroy
  has_many :chores, through: :kid_chores

  has_many :daily_chores, dependent: :destroy

  accepts_nested_attributes_for :chores, allow_destroy: true, reject_if: proc { |id| id.blank? }

  default_scope { order(name: :asc) }

  def has_chore_for_today?(chore:)
    daily_chores.for_chore(chore).for_today.present?
  end
end

app/controllers/kids_controller.rb
# frozen_string_literal: true

class KidsController < ApplicationController
  before_action :set_kid, only: %i[show edit update destroy]
  before_action :set_chores, only: %i[new create edit update]

  # GET /kids or /kids.json
  def index
    @kids = current_user.kids
  end

  # GET /kids/1 or /kids/1.json
  def show
    week = (params[:date]&.to_date || Date.current).all_week

    @week = Week.new(kid: @kid, week:)
    @streak = StreakService.call(kid: @kid)
  end

  # GET /kids/new
  def new
    @kid = Kid.new
  end

  # GET /kids/1/edit
  def edit; end

  # POST /kids or /kids.json
  def create
    @kid = Kid.new(kid_params.merge(user: current_user))

    respond_to do |format|
      if @kid.save
        format.html { redirect_to kid_url(@kid), notice: t('controllers.create', name: Kid.model_name.human) }
        format.json { render :show, status: :created, location: @kid }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kids/1 or /kids/1.json
  def update
    respond_to do |format|
      to_update = kid_params.merge(chore_ids: params.dig(:kid, :chore_ids))

      if @kid.update(to_update)
        format.html { redirect_to kid_url(@kid), notice: t('controllers.update', name: Kid.model_name.human) }
        format.json { render :show, status: :ok, location: @kid }
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1 or /kids/1.json
  def destroy
    @kid.destroy

    respond_to do |format|
      format.html { redirect_to kids_url, notice: t('controllers.destroy', name: Kid.model_name.human) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_kid
    @kid = Kid.find(params[:id])
  end

  def set_chores
    @chores = current_user.chores
  end

  # Only allow a list of trusted parameters through.
  def kid_params
    params.require(:kid).permit(:name)
  end
end

app/helpers/kids_helper.rb
# frozen_string_literal: true

module KidsHelper
end

app/views/kids/_form.html.erb
<div class="card my-2 shaddow-card">
  <div class="card-body">
    <% if title %>
      <h3 class="card-title"><%= title %></h3>
    <% end %>

    <%= form_with(model: kid) do |form| %>
      <% if kid.errors.any? %>
        <%= render 'errors', object: kid %>
      <% end %>

      <div class="mb-3">
        <%= form.label :name, class: 'form-label' %>
        <%= form.text_field :name, required: 'required', class: 'form-control' %>
      </div>

      <h6><%= t('app.kids_chores_form_title') %></h6>
      <div class="card mb-3">
        <div class="card-body">
          <%# <h5 class="card-title"><%= t('app.kids_chores_form_title') %1></h5> %>
          <h6 class="card-subtitle mb-2 text-body-secondary"><%= t('app.kids_chores_form_subtitle') %></h6>
          <%= form.collection_check_boxes :chore_ids, @chores, :id, :name do |b| %>
            <div>
              <%= b.check_box %>
              <%= b.label %>
            </div>
          <% end %>
        </div>
      </div>

      <%= form.submit class: 'btn btn-outline-dark' %>
      <%= link_to kids_path, class: 'btn btn-outline-secondary' do %>
        <%= t('app.cancel') %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/kids/_kid.html.erb
<%= turbo_frame_tag kid do %>
  <li class="list-group-item">
    <div class="d-flex w-100 justify-content-between">
      <div class="kid-list-name"><%= kid.name %></div>

      <div>
        <div class="d-flex justify-content-end">
          <%= link_to edit_kid_path(kid), data: { turbo_frame: kid }, class: 'btn btn-sm btn-outline-dark ms-2' do %>
            <i class="fa fa-pencil"></i>
          <% end %>
          <%= button_to kid, method: :delete, form: { data: { turbo_confirm: t('app.confirm_delete') } }, class: 'btn btn-sm btn-outline-dark ms-2' do %>
            <i class="fa fa-trash"></i>
          <% end %>
        </div>
      </div>
    </div>

    <div class="card mt-3">
      <div class="card-body">
        <% if kid.chores.any? %>
          <h6 class="card-subtitle mb-2 text-body-secondary"><%= t('app.kids_chores') %></h6>
          <ul class="list-group">
            <% kid.chores.each do |chore| %>
              <li class="list-group-item"><%= chore.name %></li>
            <% end %>
          </ul>
        <% else %>
          <h6 class="card-subtitle mb-2 text-body-secondary"><%= t('app.kids_no_chores') %></h6>
        <% end %>
      </div>
    </div>
  </li>
<% end %>

app/views/kids/create.turbo_stream.erb
<%= turbo_stream.append "kids", partial: "kids/kid", locals: { kid: @kid } %>
<%= turbo_stream.update Kid.new, "" %>

app/views/kids/destroy.turbo_stream.erb
<%= turbo_stream.remove @kid %>

app/views/kids/edit.html.erb
<h1><%= t('app.edit', item: Kid.model_name.human) %></h1>
<%= link_to t('app.back', item: Kid.model_name.human.pluralize), kids_path %>

<%= turbo_frame_tag @kid do %>
  <%= render "form", kid: @kid, title: nil %>
<% end %>

app/views/kids/index.html.erb
<h1><%= Kid.model_name.human.pluralize %></h1>

<%= turbo_frame_tag Kid.new do %>
  <%= link_to new_kid_path, data: { turbo_frame: dom_id(Kid.new) }, class: 'btn btn-outline-dark mb-3' do %>
    <i class="fa fa-plus"></i>
    <%= t('app.new', item: Kid.model_name.human) %>
  <% end %>
<% end %>

<ul class="list-group list-group-flush">
  <%= turbo_frame_tag 'kids' do %>
    <%= render @kids %>
  <% end %>
</ul>

app/views/kids/new.html.erb
<h1><%= t('app.new', item: Kid.model_name.human) %></h1>
<%= link_to t('app.back', item: Kid.model_name.human.pluralize), kids_path %>

<%= turbo_frame_tag @kid do %>
  <%= render "form", kid: @kid, title: t('app.new', item: Kid.model_name.human) %>
<% end %>

app/views/kids/show.html.erb
<h1><%= @kid.name %></h1>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= t('app.streak.title') %></h4>

          <h5>
            <%= @streak[:days] %>

            <%= t('app.streak.days', count: @streak[:days]) %>
          </h5>

          <h5>
            <%= @streak[:weeks_in_a_row] %>
            <%= t('app.streak.weeks', count: @streak[:weeks_in_a_row]) %>
          </h5>

          <h5>
            <%= t('app.streak.since') %>
            <%= l(@streak[:first_day].to_date) %>
          </h5>
        </div>
      </div>
    </div>

    <div class="col-sm">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"></h4>
          <%# <h4 class="card-title"><%= t('app.streak.next_payday') %1></h4> %>

          <%# <h5><%= l(@week.next.begin) %1></h5> %>
          <%# <h5><%= (12.34) %1></h5> %>
        </div>
      </div>
    </div>

    <div class="col-sm">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"></h4>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="mt-3">
  <div class="card">
    <div class="card-body">
      <%= turbo_frame_tag 'week' do %>
        <%= render 'chores_table', week: @week, kid: @kid %>
      <% end %>
    </div>
  </div>
</div>

app/views/kids/update.turbo_stream.erb
<%= turbo_stream.update @kid, @kid %>