config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kids do
    resources :daily_chores
  end
  resources :chores

  # Defines the root path route ("/")
  root 'dashboard#index'
end

app/models/chore.rb
# frozen_string_literal: true

class Chore < ApplicationRecord
  belongs_to :user

  has_many :kid_chores, dependent: :destroy
  has_many :daily_chores, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  before_save ->(chore) { chore.slug = chore.name.parameterize }
end

app/controllers/chores_controller.rb
# frozen_string_literal: true

class ChoresController < ApplicationController
  before_action :set_chore, only: %i[show edit update destroy]

  # GET /chores or /chores.json
  def index
    @chores = current_user.chores
  end

  # GET /chores/1 or /chores/1.json
  def show; end

  # GET /chores/new
  def new
    @chore = Chore.new
  end

  # GET /chores/1/edit
  def edit; end

  # POST /chores or /chores.json
  def create
    @chore = Chore.new(chore_params.merge(user: current_user))

    respond_to do |format|
      if @chore.save
        format.html { redirect_to chores_url, notice: t('controllers.chores.create') }
        format.json { render :show, status: :created, location: @chore }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chores/1 or /chores/1.json
  def update
    respond_to do |format|
      if @chore.update(chore_params)
        format.html { redirect_to chores_url, notice: t('controllers.chores.update') }
        format.json { render :show, status: :ok, location: @chore }
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1 or /chores/1.json
  def destroy
    @chore.destroy

    respond_to do |format|
      format.html { redirect_to chores_url, notice: t('controllers.chores.update') }
      format.json { head :no_content }
      format.turbo_stream
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_chore
    id = params[:id].to_i

    @chore = id ? Chore.find(id) : Chore.find_by(slug: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def chore_params
    params.require(:chore).permit(:name)
  end
end

app/helpers/chores_helper.rb
# frozen_string_literal: true

module ChoresHelper
end

app/views/chores/_chore.html.erb
<%= turbo_frame_tag chore do %>
  <li class="list-group-item">
    <div class="d-flex w-100 justify-content-between">
      <div><%= chore.name %></div>

      <div>
        <div class="d-flex justify-content-end">
          <%= link_to edit_chore_path(chore), data: { turbo_frame: chore }, class: 'btn btn-sm btn-outline-dark ms-2' do %>
            <i class="fa fa-pencil"></i>
          <% end %>
          <%= button_to chore, method: :delete, form: { data: { turbo_confirm: t('app.confirm_delete') } }, class: 'btn btn-sm btn-outline-dark ms-2' do %>
            <i class="fa fa-trash"></i>
          <% end %>
        </div>
      </div>
    </div>
  </li>
<% end %>

app/views/chores/_form.html.erb
<div class="card my-2 shaddow-card">
  <div class="card-body">
    <% if title %>
      <h3 class="card-title"><%= title %></h3>
    <% end %>

    <%= form_with(model: chore) do |form| %>
      <% if chore.errors.any? %>
        <%= render 'errors', object: chore %>
      <% end %>

      <div class="mb-3">
        <%= form.label :name, class: 'form-label' %>
        <%= form.text_field :name, required: 'required', class: 'form-control' %>
      </div>

      <%= form.submit class: 'btn btn-outline-dark' %>
      <%= link_to chores_path, class: 'btn btn-outline-secondary' do %>
        <%= t('app.cancel') %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/chores/create.turbo_stream.erb
<%= turbo_stream.append "chores", partial: "chores/chore", locals: { chore: @chore } %>
<%= turbo_stream.update Chore.new, "" %>

app/views/chores/destroy.turbo_stream.erb
<%= turbo_stream.remove @chore %>

app/views/chores/edit.html.erb
<h1><%= t('app.edit', item: Chore.model_name.human) %></h1>
<%= link_to t('app.back', item: Chore.model_name.human.pluralize), chores_path %>

<%= turbo_frame_tag @chore do %>
  <%= render "form", chore: @chore, title: nil %>
<% end %>

app/views/chores/index.html.erb
<h1><%= Chore.model_name.human.pluralize %></h1>

<%= turbo_frame_tag Chore.new do %>
  <%= link_to new_chore_path, data: { turbo_frame: dom_id(Chore.new) }, class: 'btn btn-outline-dark mb-3' do %>
    <i class="fa fa-plus"></i>
    <%= t('app.new', item: Chore.model_name.human) %>
  <% end %>
<% end %>

<ul class="list-group list-group-flush">
  <%= turbo_frame_tag 'chores' do %>
    <%= render @chores %>
  <% end %>
</ul>

app/views/chores/new.html.erb
<h1><%= t('app.new', item: Chore.model_name.human) %></h1>
<%= link_to t('app.back', item: Chore.model_name.human.pluralize), chores_path %>

<%= turbo_frame_tag @chore do %>
  <%= render "form", chore: @chore, title: t('app.new', item: Chore.model_name.human) %>
<% end %>

app/views/chores/show.html.erb
<%= render @chore %>

<div>
  <%= link_to "Edit this chore", edit_chore_path(@chore) %> |
  <%= link_to "Back to chores", chores_path %>

  <%= button_to "Destroy this chore", @chore, method: :delete %>
</div>

<h3>Records</h3>

<% @chore.daily_chores.order(created_at: :asc).each do |daily_chore| %>
  <%= daily_chore.created_at.strftime('%A, %d %b %Y') %>
<% end %>

app/views/chores/update.turbo_stream.erb
<%= turbo_stream.update @chore, @chore %>