config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kids do
    resources :daily_chores
  end
  resources :chores

  # Defines the root path route ("/")
  root 'dashboard#index'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_chores_table.html.erb
<h4 class="card-title"><%= t('app.week') %></h4>
<h6 class="card-subtitle mb-3">
  <%= l(@week.begin) %>
  <%= t('app.range.to') %>
  <%= l(@week.end) %>
</h6>

<table class="chores-table" width=100%>
<thead>
  <tr>
    <th></th>
    <% week.days.each do |day| %>
      <th>
        <%# <div><%= l(day.day) %1></div> %>
        <%# <div><%= l(day.day, format: :week_day).titleize %1></div> %>
        <div><%= l(day.day, format: :short_week_day).titleize %></div>
      </th>
    <% end %>
  </tr>
</thead>

<tbody>
  <% week.chores.each do |chore| %>
    <tr>
      <td class="chore-name"><%= chore.name %></td>

      <% week.days.each do |day| %>
        <td>
          <% if day.past? or (day.today? and day.satisfied?) %>
            <span class="badge <%= day.satisfied? ? 'text-bg-success' : 'text-bg-danger' %> px-4">
              &nbsp;
              <%# <%= day.satisfied? ? '😀' : '😞' %1> %>
            </span>
          <% else %>
            <span class="px-4">
              &nbsp;
            </span>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</tbody>

<tfoot>
  <tr>
    <td>&nbsp;</td>
    <% week.days.each do |day| %>
      <td>
        <%= number_to_currency(day.pay? ? 0.25 : 0) %>
      </td>
    <% end %>
  </tr>

  <% if week.fully_satisfied? %>
    <tr>
      <td colspan="7" class="text-end"><%= t('kids.chores.week_subtotal') %></td>
      <td><%= number_to_currency(week.satisfied_days.count * 0.25) %></td>
    </tr>

    <tr>
      <td colspan="7" class="text-end"><%= t('kids.chores.week_bonus') %></td>
      <td><%= number_to_currency(0.25) %></td>
    </tr>

    <tr class="week-total">
      <td colspan="7" class="text-end"><%= t('kids.chores.week_total') %></td>
      <td><%= number_to_currency(2.00) %></td>
    </tr>
  <% else %>
    <tr class="week-total">
      <td colspan="7" class="text-end"><%= t('kids.chores.week_total') %></td>
      <td><%= number_to_currency(week.days.select(&:satisfied?).count * 0.25) %></td>
    </tr>
  <% end %>
</tfoot>
</table>

<div class="d-flex justify-content-end mt-3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <% previous_week = week.previous.begin %>
      <% next_week = week.next.begin %>

      <li class="page-item  <%= previous_week < kid.created_at ? 'disabled' : '' %>"">
        <% if previous_week < kid.created_at %>
          <button type="button" class="page-link" disabled><%= t('app.previous_week') %></button>
        <% else %>
          <%= button_to t('app.previous_week'), kid_daily_chores_path(@kid), method: :get, params: { date: (previous_week).strftime('%Y-%m-%d')  }, class: 'page-link' %>
        <% end %>
      </li>

      <li class="page-item <%= next_week.future? ? 'disabled' : '' %>">
        <% if next_week.future? %>
          <button type="button" class="page-link" disabled><%= t('app.next_week') %></button>
        <% else %>
          <%= button_to t('app.next_week'), kid_daily_chores_path(@kid), method: :get, params: { date: (next_week).strftime('%Y-%m-%d')  }, class: 'page-link' %>
        <% end %>
      </li>
    </ul>
  </nav>
</div>

app/views/application/_errors.html.erb
<div class="alert alert-danger" role="alert">
  <div><%= t('app.prohibited', count: object.errors.count) %></div>
  <ul>
    <% object.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>

app/views/application/_menu.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= t('home') %>
      <%# <%= image_tag('logo.png', alt: 'Logo') %1> %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to chores_path, class: 'nav-link' do %>
            <%= t('app.chores') %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to kids_path, class: 'nav-link' do %>
            <%= t('app.kids') %>
          <% end %>
        </li>
        <%# <li class="nav-item"> %>
        <%#   <%= link_to new_daily_chore_path, class: 'nav-link' do %1> %>
        <%#     <%= t('app.new_daily_chore') %1> %>
        <%#   <% end %1> %>
        <%# </li> %>
      </ul>
      <ul class="navbar-nav d-flex">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= t('app.user_actions') %>
          </a>
          <ul class="dropdown-menu">
            <%= button_to destroy_user_session_path, method: :delete, form: { data: { turbo: false } }, class: 'dropdown-item' do %>
              <%= t('app.logout') %>
            <% end %>
            </li>
          </ul>
        </li>
        </ul>
    </div>
  </div>
</nav>